
version: '3.3'

services:
  database:
    container_name: influxdb
    image: influxdb
    restart: always
    volumes:
     -  /tmp/testdata/influx:/root/.influxdbv2
    ports:
      - "8086:8086"
    networks:
      default:
        aliases:
          - influxdb
  grafana:
    container_name: grafana
    image: grafana/grafana
    build:
      context: .
      dockerfile: Dockerfile.grafana
    restart: always
    ports:
      - "3000:3000"
  api:
    container_name: api
    image: taller4/api
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.api
    volumes:
      - ./app:/app
    ports:
      - "80:80"
    networks:
      default:
        aliases:
          - api
  notepad:
    container_name: notepad
    image: taller3/notepad
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.python
    volumes:
     - ./app:/app
    ports:
      - "8888:8888"
    depends_on:
      - rabbit
  rabbit:
    container_name: rabbit
    image: taller3/rabbit
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.rabbit
    ports:
      - "15672:15672"
      - "5672:5672"
      - "1883:1883"
    networks:
      default:
        aliases:
          - rabbit

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/24
